spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: Dima228*

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
    consumer:
      group-id: bank-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: transferEvent:com.infy.dto.TransferEvent
      enable-auto-commit: false
      max-poll-records: 100
      fetch-min-bytes: 1024
      fetch-max-wait-ms: 1000
    listener:
      type: batch
      ack-mode: manual_immediate

server:
  port: 8081
