spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: Dima228*

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080