# ????????? ???????? ????????
book.stale.months=3
book.auto.close.requests=true



spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookstore}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Dima228*}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:changelog/changelog-master.yaml
spring.liquibase.enabled=true

spring.aop.proxy-target-class=true

jwt.secret=zX8mP2kL9nQ4rT7vW1yE5aH8cK3nR6uV9xZ2bE7fJ1mP4qT8wX3cK6nR9uV2
jwt.expiration-ms=86400000

